name: Test Script
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
      - 'github-actions/test'
jobs:
  check:
    name: check test
    runs-on: ubuntu-latest
    steps:
      - name: check test
        run: sleep 60 && echo "Hello World"
