name: Test Script
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
  push:
jobs:
  check:
    name: check test
    if: (github.event_name != 'IssueCommentEvent') || github.event.comment.body == '!github call rspec'
    runs-on: ubuntu-latest
    steps:
      - name: check test
        run: sleep 10 && echo "Completed!!"
