name: Test Script
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
jobs:
  check:
    name: check test
    if: (github.event.issue.pull_request != null) && github.event.comment.body == '!github call rspec'
    runs-on: ubuntu-latest
    steps:
      - name: check test
        run: sleep 10 && echo "Completed!!"
