name: Test Script
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
  push:
  pull_request:
    types:
      - labeled
jobs:
  check:
    name: check test
    if: (github.event.action != 'labeled') || github.event.label.name == 'call-rspec'
    runs-on: ubuntu-latest
    steps:
      - name: check test
        run: sleep 10 && echo "Completed!!" && exit 1
