name: Test Script
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
jobs:
  check:
    name: check test
    runs-on: ubuntu-latest
    steps:
      - name: check test
        run: sleep 10 && echo "Hello World"
